version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - cert_volume:/home/app/web/certfiles
    expose:
      - 8000
    env_file:
      - env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - cert_volume:/home/app/web/certfiles
    ports:
      - '1337:80'
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  cert_volume:
