# Generated by Django 3.2 on 2023-01-09 19:07

from django.db import migrations, models
import hello_django.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFBucketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=hello_django.storage_backends.PDFBucket(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StaticStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=hello_django.storage_backends.StaticStorage(), upload_to='')),
            ],
        ),
    ]
